artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/entbappy/Branching-tutorial/raw/master/tmdb_5000_credits.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data

  
data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  credit_csv_file: tmdb_5000_credits.csv
  movies_csv_file: tmdb_5000_movies.csv
